# Copy this to ${AUTHELIA_STORAGE_PATH}/data/users_database.yml before first startup.
users:
  buggi:
    displayname: "buggi"
    password: "$argon2id$v=19$m=65536,t=3,p=4$iRWg3pfY/tEg4A9rNefbDA$0B3JphaLjRhIf4mglH92lqitKBufwzRHiSk/wPr8PSw"
    groups:
      - admins
  buggi-user:
    displayname: "buggi-user"
    password: "$argon2id$v=19$m=65536,t=3,p=4$jYU/n7VArzsVufizgxBjrA$M+AgUTJSo+XGA/pCuhQ5t3/OHtm8Kw1f1pz1Mp+vonI"
